
package mini_project;
import javax.swing.JOptionPane;

public class LetterPostShop extends javax.swing.JFrame {

    /**
     * Creates new form LetterPostShop
     */
    public LetterPostShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rbtnNormal = new javax.swing.JRadioButton();
        rbtnRegis = new javax.swing.JRadioButton();
        rbtnEms = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtWeightPost = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Letter Post Shop");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Letter Post Shop", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Earth Orbiter Bold", 0, 36))); // NOI18N

        btnCalculate.setFont(new java.awt.Font("FC Minimal", 0, 24)); // NOI18N
        btnCalculate.setText("คำนวณราคา");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("FC Minimal", 0, 24)); // NOI18N
        jLabel2.setText("ประเภทจดหมาย");

        buttonGroup1.add(rbtnNormal);
        rbtnNormal.setFont(new java.awt.Font("FC Minimal", 0, 24)); // NOI18N
        rbtnNormal.setText("Normal");
        rbtnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnRegis);
        rbtnRegis.setFont(new java.awt.Font("FC Minimal", 0, 24)); // NOI18N
        rbtnRegis.setText("Register");
        rbtnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRegisActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnEms);
        rbtnEms.setFont(new java.awt.Font("FC Minimal", 0, 24)); // NOI18N
        rbtnEms.setText("EMS");
        rbtnEms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEmsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("FC Minimal", 0, 24)); // NOI18N
        jLabel3.setText("น้ำหนักจดหมาย (g)");

        txtWeightPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightPostActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("FC Minimal", 0, 24)); // NOI18N
        btnClear.setText("Claer");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("FC Minimal", 0, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(rbtnNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnRegis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnEms)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtWeightPost, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculate)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbtnNormal)
                    .addComponent(rbtnRegis)
                    .addComponent(rbtnEms))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtWeightPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void rbtnNormalActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here: t
    }                                          

    private void rbtnRegisActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txtWeightPostActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String post = "";
        int weight = Integer.parseInt(txtWeightPost.getText());
        String price = "";
        
        if (rbtnNormal.isSelected()) {
            if (weight < 21) {
                price = "3";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
                
            }
            else if (weight > 20 && weight < 101) {
                price = "5";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 100 && weight < 251) {
                price = "9";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 250 && weight < 501) {
                price = "15";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 500 && weight < 1001) {
                price = "25";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else {
                price = "45";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
        }

    public LetterPostShop(javax.swing.JButton btnCalculate, javax.swing.JButton btnClear, javax.swing.JButton btnExit, javax.swing.ButtonGroup buttonGroup1, javax.swing.ButtonGroup buttonGroup2, javax.swing.ButtonGroup buttonGroup3, javax.swing.ButtonGroup buttonGroup4, javax.swing.ButtonGroup buttonGroup5, javax.swing.ButtonGroup buttonGroup6, javax.swing.ButtonGroup buttonGroup7, javax.swing.JLabel jLabel2, javax.swing.JLabel jLabel3, javax.swing.JPanel jPanel1, javax.swing.JScrollPane jScrollPane1, javax.swing.JRadioButton rbtnEms, javax.swing.JRadioButton rbtnNormal, javax.swing.JRadioButton rbtnRegis, javax.swing.JTextArea txtArea, javax.swing.JTextField txtWeightPost) {
        this.btnCalculate = btnCalculate;
        this.btnClear = btnClear;
        this.btnExit = btnExit;
        this.buttonGroup1 = buttonGroup1;
        this.buttonGroup2 = buttonGroup2;
        this.buttonGroup3 = buttonGroup3;
        this.buttonGroup4 = buttonGroup4;
        this.buttonGroup5 = buttonGroup5;
        this.buttonGroup6 = buttonGroup6;
        this.buttonGroup7 = buttonGroup7;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.rbtnEms = rbtnEms;
        this.rbtnNormal = rbtnNormal;
        this.rbtnRegis = rbtnRegis;
        this.txtArea = txtArea;
        this.txtWeightPost = txtWeightPost;
    }

    public javax.swing.JButton getBtnCalculate() {
        return this.btnCalculate;
    }

    public void setBtnCalculate(javax.swing.JButton btnCalculate) {
        this.btnCalculate = btnCalculate;
    }

    public javax.swing.JButton getBtnClear() {
        return this.btnClear;
    }

    public void setBtnClear(javax.swing.JButton btnClear) {
        this.btnClear = btnClear;
    }

    public javax.swing.JButton getBtnExit() {
        return this.btnExit;
    }

    public void setBtnExit(javax.swing.JButton btnExit) {
        this.btnExit = btnExit;
    }

    public javax.swing.ButtonGroup getButtonGroup1() {
        return this.buttonGroup1;
    }

    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public javax.swing.ButtonGroup getButtonGroup2() {
        return this.buttonGroup2;
    }

    public void setButtonGroup2(javax.swing.ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    public javax.swing.ButtonGroup getButtonGroup3() {
        return this.buttonGroup3;
    }

    public void setButtonGroup3(javax.swing.ButtonGroup buttonGroup3) {
        this.buttonGroup3 = buttonGroup3;
    }

    public javax.swing.ButtonGroup getButtonGroup4() {
        return this.buttonGroup4;
    }

    public void setButtonGroup4(javax.swing.ButtonGroup buttonGroup4) {
        this.buttonGroup4 = buttonGroup4;
    }

    public javax.swing.ButtonGroup getButtonGroup5() {
        return this.buttonGroup5;
    }

    public void setButtonGroup5(javax.swing.ButtonGroup buttonGroup5) {
        this.buttonGroup5 = buttonGroup5;
    }

    public javax.swing.ButtonGroup getButtonGroup6() {
        return this.buttonGroup6;
    }

    public void setButtonGroup6(javax.swing.ButtonGroup buttonGroup6) {
        this.buttonGroup6 = buttonGroup6;
    }

    public javax.swing.ButtonGroup getButtonGroup7() {
        return this.buttonGroup7;
    }

    public void setButtonGroup7(javax.swing.ButtonGroup buttonGroup7) {
        this.buttonGroup7 = buttonGroup7;
    }

    public javax.swing.JLabel getJLabel2() {
        return this.jLabel2;
    }

    public void setJLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public javax.swing.JLabel getJLabel3() {
        return this.jLabel3;
    }

    public void setJLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public javax.swing.JPanel getJPanel1() {
        return this.jPanel1;
    }

    public void setJPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JScrollPane getJScrollPane1() {
        return this.jScrollPane1;
    }

    public void setJScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JRadioButton getRbtnEms() {
        return this.rbtnEms;
    }

    public void setRbtnEms(javax.swing.JRadioButton rbtnEms) {
        this.rbtnEms = rbtnEms;
    }

    public javax.swing.JRadioButton getRbtnNormal() {
        return this.rbtnNormal;
    }

    public void setRbtnNormal(javax.swing.JRadioButton rbtnNormal) {
        this.rbtnNormal = rbtnNormal;
    }

    public javax.swing.JRadioButton getRbtnRegis() {
        return this.rbtnRegis;
    }

    public void setRbtnRegis(javax.swing.JRadioButton rbtnRegis) {
        this.rbtnRegis = rbtnRegis;
    }

    public javax.swing.JTextArea getTxtArea() {
        return this.txtArea;
    }

    public void setTxtArea(javax.swing.JTextArea txtArea) {
        this.txtArea = txtArea;
    }

    public javax.swing.JTextField getTxtWeightPost() {
        return this.txtWeightPost;
    }

    public void setTxtWeightPost(javax.swing.JTextField txtWeightPost) {
        this.txtWeightPost = txtWeightPost;
    }

    public LetterPostShop btnCalculate(javax.swing.JButton btnCalculate) {
        setBtnCalculate(btnCalculate);
        return this;
    }

    public LetterPostShop btnClear(javax.swing.JButton btnClear) {
        setBtnClear(btnClear);
        return this;
    }

    public LetterPostShop btnExit(javax.swing.JButton btnExit) {
        setBtnExit(btnExit);
        return this;
    }

    public LetterPostShop buttonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        setButtonGroup1(buttonGroup1);
        return this;
    }

    public LetterPostShop buttonGroup2(javax.swing.ButtonGroup buttonGroup2) {
        setButtonGroup2(buttonGroup2);
        return this;
    }

    public LetterPostShop buttonGroup3(javax.swing.ButtonGroup buttonGroup3) {
        setButtonGroup3(buttonGroup3);
        return this;
    }

    public LetterPostShop buttonGroup4(javax.swing.ButtonGroup buttonGroup4) {
        setButtonGroup4(buttonGroup4);
        return this;
    }

    public LetterPostShop buttonGroup5(javax.swing.ButtonGroup buttonGroup5) {
        setButtonGroup5(buttonGroup5);
        return this;
    }

    public LetterPostShop buttonGroup6(javax.swing.ButtonGroup buttonGroup6) {
        setButtonGroup6(buttonGroup6);
        return this;
    }

    public LetterPostShop buttonGroup7(javax.swing.ButtonGroup buttonGroup7) {
        setButtonGroup7(buttonGroup7);
        return this;
    }

    public LetterPostShop jLabel2(javax.swing.JLabel jLabel2) {
        setJLabel2(jLabel2);
        return this;
    }

    public LetterPostShop jLabel3(javax.swing.JLabel jLabel3) {
        setJLabel3(jLabel3);
        return this;
    }

    public LetterPostShop jPanel1(javax.swing.JPanel jPanel1) {
        setJPanel1(jPanel1);
        return this;
    }

    public LetterPostShop jScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        setJScrollPane1(jScrollPane1);
        return this;
    }

    public LetterPostShop rbtnEms(javax.swing.JRadioButton rbtnEms) {
        setRbtnEms(rbtnEms);
        return this;
    }

    public LetterPostShop rbtnNormal(javax.swing.JRadioButton rbtnNormal) {
        setRbtnNormal(rbtnNormal);
        return this;
    }

    public LetterPostShop rbtnRegis(javax.swing.JRadioButton rbtnRegis) {
        setRbtnRegis(rbtnRegis);
        return this;
    }

    public LetterPostShop txtArea(javax.swing.JTextArea txtArea) {
        setTxtArea(txtArea);
        return this;
    }

    public LetterPostShop txtWeightPost(javax.swing.JTextField txtWeightPost) {
        setTxtWeightPost(txtWeightPost);
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof LetterPostShop)) {
            return false;
        }
        LetterPostShop letterPostShop = (LetterPostShop) o;
        return Objects.equals(btnCalculate, letterPostShop.btnCalculate) && Objects.equals(btnClear, letterPostShop.btnClear) && Objects.equals(btnExit, letterPostShop.btnExit) && Objects.equals(buttonGroup1, letterPostShop.buttonGroup1) && Objects.equals(buttonGroup2, letterPostShop.buttonGroup2) && Objects.equals(buttonGroup3, letterPostShop.buttonGroup3) && Objects.equals(buttonGroup4, letterPostShop.buttonGroup4) && Objects.equals(buttonGroup5, letterPostShop.buttonGroup5) && Objects.equals(buttonGroup6, letterPostShop.buttonGroup6) && Objects.equals(buttonGroup7, letterPostShop.buttonGroup7) && Objects.equals(jLabel2, letterPostShop.jLabel2) && Objects.equals(jLabel3, letterPostShop.jLabel3) && Objects.equals(jPanel1, letterPostShop.jPanel1) && Objects.equals(jScrollPane1, letterPostShop.jScrollPane1) && Objects.equals(rbtnEms, letterPostShop.rbtnEms) && Objects.equals(rbtnNormal, letterPostShop.rbtnNormal) && Objects.equals(rbtnRegis, letterPostShop.rbtnRegis) && Objects.equals(txtArea, letterPostShop.txtArea) && Objects.equals(txtWeightPost, letterPostShop.txtWeightPost);
    }

    @Override
    public int hashCode() {
        return Objects.hash(btnCalculate, btnClear, btnExit, buttonGroup1, buttonGroup2, buttonGroup3, buttonGroup4, buttonGroup5, buttonGroup6, buttonGroup7, jLabel2, jLabel3, jPanel1, jScrollPane1, rbtnEms, rbtnNormal, rbtnRegis, txtArea, txtWeightPost);
    }

    @Override
    public String toString() {
        return "{" +
            " btnCalculate='" + getBtnCalculate() + "'" +
            ", btnClear='" + getBtnClear() + "'" +
            ", btnExit='" + getBtnExit() + "'" +
            ", buttonGroup1='" + getButtonGroup1() + "'" +
            ", buttonGroup2='" + getButtonGroup2() + "'" +
            ", buttonGroup3='" + getButtonGroup3() + "'" +
            ", buttonGroup4='" + getButtonGroup4() + "'" +
            ", buttonGroup5='" + getButtonGroup5() + "'" +
            ", buttonGroup6='" + getButtonGroup6() + "'" +
            ", buttonGroup7='" + getButtonGroup7() + "'" +
            ", jLabel2='" + getJLabel2() + "'" +
            ", jLabel3='" + getJLabel3() + "'" +
            ", jPanel1='" + getJPanel1() + "'" +
            ", jScrollPane1='" + getJScrollPane1() + "'" +
            ", rbtnEms='" + getRbtnEms() + "'" +
            ", rbtnNormal='" + getRbtnNormal() + "'" +
            ", rbtnRegis='" + getRbtnRegis() + "'" +
            ", txtArea='" + getTxtArea() + "'" +
            ", txtWeightPost='" + getTxtWeightPost() + "'" +
            "}";
    }
        
        else if (rbtnRegis.isSelected()) {
            if (weight < 21) {
                price = "16";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
                
            }
            else if (weight > 20 && weight < 101) {
                price = "18";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 100 && weight < 251) {
                price = "22";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 250 && weight < 501) {
                price = "28";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 500 && weight < 1001) {
                price = "38";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else {
                price = "58";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
        }

        else if (rbtnEms.isSelected()) {
            if (weight < 21) {
                price = "27";
                
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 20 && weight < 101) {
                price = "32";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 100 && weight < 251) {
                price = "37";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 250 && weight < 501) {
                price = "47";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else if (weight > 500 && weight < 1001) {
                price = "62";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
            else {
                price = "77";
                txtArea.setText("ราคาค่าจัดส่ง : "+price+" บาท");
            }
        }

    }                                            

    private void rbtnEmsActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        txtWeightPost.setText("");
        txtArea.setText("");
    }                                        

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int option = JOptionPane.showConfirmDialog(rootPane, "Do you want to Exit ?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
            
        }
        
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LetterPostShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnEms;
    private javax.swing.JRadioButton rbtnNormal;
    private javax.swing.JRadioButton rbtnRegis;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtWeightPost;
    // End of variables declaration                   
}